import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRecoilState } from 'recoil'
import { myAtoms } from './reco'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [reccount, setRecCount] = useRecoilState(myAtoms.myCount)
  const [recstr, setRecStr] = useRecoilState(myAtoms.myString)

  const increment = () => {
    setRecCount(reccount + 1);
    setRecStr(recstr + '!');
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>

        <div className={styles.center}>asdf</div>
        <p>Count: {reccount}</p>
        <p>String: {recstr}</p>
        <button onClick={increment}>Increment</button>
      </main>
    </>
  )
}
